HW0 submitted by Bichen07(Attempt3)
yungyuc/nsdhw_24au pull request #22
Opened 2024-09-15 08:09 UTC by Bichen07

---
implement hw0. By adding validate.sh and countline.py into it. 
cd nsdhw_24au/hw0/Bichen07
../validate.sh
will show result get points

A good PR should include the following parts:

- [ ] Provide a clear title
- [ ] Provide meaningful descriptions in the PR and the commit logs
- [ ] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [ ] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [ ] Exclude irrelevant files, such as binaries, text files, or dot files
- [ ] Make sure tests/CI pass

2024-09-15 11:56 UTC, ThreeMonth03 requested changes
I know that you are a diligent student, but you should make a pr to [yungyuc:hw0](https://github.com/yungyuc/nsdhw_24au/tree/hw0) instead of [yungyuc:master](https://github.com/yungyuc/nsdhw_24au/tree/master). Please try again.

2024-09-16 04:03 UTC, Bichen07 commented
thank for reminding me. I have make a pr to yungyuc:hw0.

2024-09-16 10:41 UTC, ThreeMonth03 approved these changes

2024-09-16 11:22 UTC, ThreeMonth03 requested changes
Could you please close this pr and make another pr again? It seems that the yaml in `.github/workflows/` [doesn't trigger the github action](https://stackoverflow.com/questions/77495124/trigger-a-github-workflow-on-target-branch-changed) when you change the base branch directly.

2024-09-17 08:24 UTC, closed without merging