Submit oscarshiang's project proposal
yungyuc/nsdhw_24au pull request #31
Opened 2024-09-17 06:33 UTC by OscarShiang

Create `oscarshiang/README.rst` to describe the details and the schedule of the project.

---
A good PR should include the following parts:

- [x] Provide a clear title
- [x] Provide meaningful descriptions in the PR and the commit logs
- [x] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [x] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [x] Exclude irrelevant files, such as binaries, text files, or dot files
- [x] Make sure tests/CI pass

2024-09-17 08:50 UTC, yungyuc requested changes
- [x] Add an entry in `project/README.rst` pointing to your proposal.
- [x] Change to use less than 80 characters in a line.  Long lines are hard to review and annotate.
- [x] [L5](https://github.com/yungyuc/nsdhw_24au/pull/31/files#diff-7ae2f9e3546651a97bd5b524fd37bdbeb8860b16a1d06642253c887a929f7d90R5): Github repository.
- [x] [L24](https://github.com/yungyuc/nsdhw_24au/pull/31/files#diff-7ae2f9e3546651a97bd5b524fd37bdbeb8860b16a1d06642253c887a929f7d90R24): Explicit list of operations.
- [ ] [L68](https://github.com/yungyuc/nsdhw_24au/pull/31/files#diff-7ae2f9e3546651a97bd5b524fd37bdbeb8860b16a1d06642253c887a929f7d90R68): Pull forward testing and CI.

2024-09-17 08:50 UTC, yungyuc commented on project/OscarShiang/README.rst
> +PicoLA
I like the name.

2024-09-17 08:50 UTC, yungyuc commented on project/OscarShiang/README.rst
> +`PicoLA` aims to provide coding experience similiar to MATLAB and is capable to run on resource-limited devices without installing extra dependent packages.
Very clear goal.

2024-09-17 08:50 UTC, yungyuc commented on project/OscarShiang/README.rst
> +PicoLA: a compact C++ library for doing linear algebra computations
Please supply the github repository.

2024-09-17 08:50 UTC, yungyuc commented on project/OscarShiang/README.rst
> +2. Related operations (e.g. add, substract, multiply, cross, normalize, sum, average, ...)
Please write down a complete list of operations to support in your project.

2024-09-17 08:50 UTC, yungyuc commented on project/OscarShiang/README.rst
> +- Week 1: Setup the infrastructures
Please add dates in the schedule.

2024-09-17 08:50 UTC, yungyuc commented on project/OscarShiang/README.rst
> +- Week 6: Create unit tests and set onto GitHub Actions
Unit testing and CI are to improve your productivity.  Doing them in the final phase of your development defeats the purpose.  Please revise the plan to start them in the beginning.

2024-09-18 05:50 UTC, OscarShiang commented
I have updated README.rst with the following changes:
- Add repo link in basic information section
- Specify all the operations need to be implemented
- Revise and add expected date into the schedule
- Translate the link syntax from markdown into rst
- Break all line that is has more than 80 characters

2024-09-18 06:01 UTC, OscarShiang commented
The entry of my project has also been added into `project/README.rst`.

2024-09-18 10:36 UTC, yungyuc approved these changes
> I have updated README.rst with the following changes:
> 
> * Add repo link in basic information section
> * Specify all the operations need to be implemented
> * Revise and add expected date into the schedule
> * Translate the link syntax from markdown into rst
> * Break all line that is has more than 80 characters
>
> The entry of my project has also been added into `project/README.rst`.

LGTM.  Let me know if you want the PR to be merged.

2024-10-05 06:21 UTC, OscarShiang commented
I am ready to be merged!

2024-10-05 12:43 UTC, merged