Sean20405 proposal for fftconvolve2d
yungyuc/nsdhw_24au pull request #43
Opened 2024-09-18 02:32 UTC by Sean20405

---
A good PR should include the following parts:

- [x] Provide a clear title
- [x] Provide meaningful descriptions in the PR and the commit logs
- [x] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [x] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [x] Exclude irrelevant files, such as binaries, text files, or dot files
- [x] Make sure tests/CI pass

2024-09-18 09:16 UTC, yungyuc requested changes
To request for a next review, please leave a global message summarizing what you change.

- [ ] [L50](https://github.com/yungyuc/nsdhw_24au/pull/43/files#diff-4e4bfc35470ae48b373f517d977aa1ba1be173b65d98d844a742d1c8847f2adcR50): Clarify if you will use a definition for "array-like".
- [ ] [L114](https://github.com/yungyuc/nsdhw_24au/pull/43/files#diff-4e4bfc35470ae48b373f517d977aa1ba1be173b65d98d844a742d1c8847f2adcR114): Add Github Actions into the testing plan.

2024-09-18 09:16 UTC, yungyuc commented on project/Sean20405/README.rst
> +   array-like kernel. The dimension of both inputs should be 2
Do you have a definition of "array-like"?

2024-09-18 09:16 UTC, yungyuc commented on project/Sean20405/README.rst
> +- Week 1 (09/29): Learn FFT
A fast way to learn is to find a reference code.

2024-09-18 09:16 UTC, yungyuc commented on project/Sean20405/README.rst
> +- Week 3 (10/13): Write test for FFT and FFT convolution
Please include setting up Github Actions along with the test development.

2024-09-18 17:05 UTC, Sean20405 commented
I'm ready for the second attempt of my proposal. Thanks for such useful feedback!

2024-09-19 13:54 UTC, yungyuc requested changes
LGTM.  You need to add an entry in `project/README.rst` pointing to your proposal.

2024-09-19 17:37 UTC, Sean20405 commented
I'm ready for the third attempt of my proposal.
Thanks for reminder! And I've also resolve the conflict derived from index in `project/README`.

2024-09-20 03:15 UTC, yungyuc approved these changes
Let me know when you want this PR to be merged.

2024-10-07 12:22 UTC, merged