ian31174117 proposal for SimpleEigenSolver
yungyuc/nsdhw_24au pull request #45
Opened 2024-09-18 05:55 UTC by ian31174117

---
A good PR should include the following parts:

- [ x ] Provide a clear title
- [ x ] Provide meaningful descriptions in the PR and the commit logs
- [ x ] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [ x ] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [ x ] Exclude irrelevant files, such as binaries, text files, or dot files
- [ x ] Make sure tests/CI pass

2024-09-18 10:28 UTC, yungyuc requested changes
When requesting for a next review, please leave a global comment summarizing your change.

- [x] Please change to use less than 80 characters in a line.  Long lines make it hard to annotate and discuss.
- [ ] [L100](https://github.com/yungyuc/nsdhw_24au/pull/45/files#diff-65f679f357567bc74de3bcd1bbd531539ef022ffe02c4adda73407e1756ceb18R100): Do automatic testing and CI early.

2024-09-18 10:28 UTC, yungyuc commented on project/ian31174117/README.rst
> +There have been several libraries to calculate Eigen values and vectors, such as `Eigen <https://eigen.tuxfamily.org/index.php?title=Main_Page>`_ and `LAPACK <https://www.netlib.org/lapack/>`_. Howev
Eigen is a good C++ reference and LAPACK is the de facto interface for linear algebra code.

2024-09-18 10:28 UTC, yungyuc commented on project/ian31174117/README.rst
> +1. QR algorithm to calculate Eigen values and vectors
It will be wonderful if you can complete any of the four listed items in the semester.

2024-09-18 10:28 UTC, yungyuc commented on project/ian31174117/README.rst
> +    #include<"SimpleEigenCalculator.h">
Syntax error.  But it's fine in the proposal.

2024-09-18 10:28 UTC, yungyuc commented on project/ian31174117/README.rst
> +        std::vector<std::vector<float>> matrix = sample_matrix; // a 2D vector representing a matrix
Vector of vectors is a sure way to kill performance.

2024-09-18 10:28 UTC, yungyuc commented on project/ian31174117/README.rst
> +* Week 8: Final testing and presentation
Please revise the plan to do automatic testing and CI in the early stage in the development.  They will help you work productively.  Don't make them like amendment.

2024-09-18 11:38 UTC, ian31174117 commented on project/ian31174117/README.rst
> +        std::vector<std::vector<float>> matrix = sample_matrix; // a 2D vector representing a matrix
I'll revise this part. However there might be some lazy users relying on such an inefficient structure. 
Will it be a good idea to enable constructon from vectors or something else? The convertion may be taken into consideration too.

2024-09-18 12:05 UTC, ian31174117 commented
@yungyuc Thanks for the detailed reply. Several changes have been made to the proposal:
- [ ] Formatted the rst file to 80 characters per line and syntax using formatter
- [ ] Re-plan the testing and CI workflow
- [ ] Revised the description of libraries reference
- [ ] Re-design the data structure to avoid obvious performance issue

Please review the revised proposal when convenient, thanks!

2024-09-19 13:13 UTC, yungyuc approved these changes
> @yungyuc Thanks for the detailed reply. Several changes have been made to the proposal:
> 
> * [ ]  Formatted the rst file to 80 characters per line and syntax using formatter
> * [ ]  Re-plan the testing and CI workflow
> * [ ]  Revised the description of libraries reference
> * [ ]  Re-design the data structure to avoid obvious performance issue
> 
> Please review the revised proposal when convenient, thanks!

LGTM.  Let me know when you want the PR to be merged.

2024-09-23 01:17 UTC, ian31174117 commented
I think this PR is ready to be merged, thanks

2024-09-24 07:04 UTC, merged