hfkfo proposal for Boolean Operations on Polygons
yungyuc/nsdhw_24au pull request #46
Opened 2024-09-18 05:59 UTC by hfkfo

A good PR should include the following parts:

- [ ] Provide a clear title
- [ ] Provide meaningful descriptions in the PR and the commit logs
- [ ] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [ ] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [ ] Exclude irrelevant files, such as binaries, text files, or dot files
- [ ] Make sure tests/CI pass

2024-09-18 10:32 UTC, yungyuc commented
@hfkfo you should have created the PR against `project` branch.  I correct it for you.

2024-09-18 10:33 UTC, yungyuc requested changes
When requesting for a next review, please leave a global comment summarizing your change.

- [ ] Change to use less than 80 characters in a line.  Long lines make it hard to annotate and discuss.
- [ ] Add an entry in `project/README.rst` pointing to your proposal.

I will review again after you are ready.

2024-09-18 10:34 UTC, yungyuc commented
Please add an entry in E3 too.  I can't find it.

2024-09-19 05:47 UTC, hfkfo commented
I'm ready for next review

2024-09-19 13:56 UTC, yungyuc requested changes
- [ ] [L81](https://github.com/yungyuc/nsdhw_24au/pull/46/files#diff-3b52f937846d878bd1b684a7b2eee3b818aa5a11cc61da36a7617071c7499545R81): Specify how to visualize.

2024-09-19 13:56 UTC, yungyuc commented on project/hfkfo/README.rst
> +
There should not be a blank line between lines in the same paragraph.

2024-09-19 13:56 UTC, yungyuc commented on project/hfkfo/README.rst
> +* Week 1-2 (09/30): Setup the infrastructures and learn how to do CI in github.
You will have a good start if basic testing and CI are ready by the end of the month.

2024-09-19 13:56 UTC, yungyuc commented on project/hfkfo/README.rst
> +* Week 5 (10/28): Write python code to visualize the result.
Please specify how do you plan to visualize it.  Visualization is hard.

2024-09-19 13:57 UTC, yungyuc commented
Please also resolve merge conflict.

2024-09-24 12:15 UTC, hfkfo commented
I'm ready for next review

2024-09-24 23:44 UTC, merged