Kang-Ding-Xin-NYCU proposal for PolygonAreaCalculator
yungyuc/nsdhw_24au pull request #50
Opened 2024-09-18 11:47 UTC by Kang-Ding-Xin-NYCU

---
A good PR should include the following parts:

- [x] Provide a clear title
- [x] Provide meaningful descriptions in the PR and the commit logs
- [x] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [x] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [x] Exclude irrelevant files, such as binaries, text files, or dot files
- [x] Make sure tests/CI pass

2024-09-19 13:09 UTC, yungyuc requested changes
You wrongly deleted `project/README.rst`.  Please fix it before proceeding.

Your commit history should not contain the wrong removal of the file.  When fixing the wrong deletion, please squash too.

When requesting for a next review, please leave a global comment summarizing what you change.

2024-09-20 01:56 UTC, Kang-Ding-Xin-NYCU commented
Use git reset to reset the branch and copy the file that I already wrote.
Finally, git push -f

2024-09-20 03:20 UTC, yungyuc requested changes
- [x] Please add an entry in `project/README.rst` pointing to your proposal.
- [ ] Specify the value data type of coordinates.
- [ ] Include automatic testing and CI.
- [ ] Specify how to handle holes.

2024-09-20 03:20 UTC, yungyuc commented on project/Kang-Ding-Xin-NYCU/README.rst
> +        vector<vertices> verticeslist;
Please specify the value data type of the coordinates.

2024-09-20 03:20 UTC, yungyuc commented on project/Kang-Ding-Xin-NYCU/README.rst
> +* Week 1 (09/20):survey the method to implement the area calculation and drawing image
Please include automatic testing and CI early in the schedule.  Think about how it improves your development productivity.

2024-09-20 03:20 UTC, yungyuc commented on project/Kang-Ding-Xin-NYCU/README.rst
> +* Easily get the the area of polygons and the image of polygons
Please specify how the code handles holes in polygons and nested holes.  (There are basically two styles to represent holes: cutlines and islands.)

2024-10-07 10:33 UTC, yungyuc commented
@Kang-Ding-Xin-NYCU please fix all issues and update as soon as possible.  I will stop accepting proposals any time.  It's long overdue.

2024-10-07 12:22 UTC, Kang-Ding-Xin-NYCU commented
- [x]Please add an entry in project/README.rst pointing to your proposal.
 - [x]Specify the value data type of coordinates.
 - [x]Include automatic testing and CI.
 - [x]Specify how to handle holes.

2024-10-07 12:24 UTC, yungyuc commented
> * [ ]  Please add an entry in project/README.rst pointing to your proposal.

You have not done it.

2024-10-07 12:34 UTC, yungyuc commented
Please review merged PRs: https://github.com/yungyuc/nsdhw_24au/pulls?q=is%3Apr+label%3Aproject+is%3Aclosed

2024-10-07 12:53 UTC, Kang-Ding-Xin-NYCU commented
I have changed the link but I am not very sure that is right

2024-10-07 13:03 UTC, yungyuc commented
> I have changed the link but I am not very sure that is right

You have not got it correctly.  You need to add an entry in the file `project/README.rst`, not in your proposal file.  Please review the merged PRs.

@jteng2127, if you have time, could you please help @Kang-Ding-Xin-NYCU for his PR?

2024-10-07 13:32 UTC, Kang-Ding-Xin-NYCU commented
Oh, I got it. I have add an entry in project/README.rst.

2024-10-07 13:35 UTC, jteng2127 commented
Yes, I could help

If there is still any issue, @Kang-Ding-Xin-NYCU when are you available?

2024-10-07 13:44 UTC, yungyuc approved these changes
Plain text should use less than 80 characters in a line.  Long lines are hard to review and comment.

The proposal is OK.  Please start prototyping.

2024-10-07 13:45 UTC, merged

2024-10-07 13:50 UTC, jteng2127 commented
@yungyuc I think the entry in `project/README.rst` is misplaced

<img width="939" alt="image" src="https://github.com/user-attachments/assets/f103888f-2f4b-4129-983d-634f10965bb5">

2024-10-07 14:22 UTC, yungyuc commented
> @yungyuc I think the entry in `project/README.rst` is misplaced
> 
> <img alt="image" width="939" src="https://private-user-images.githubusercontent.com/39561523/374194643-f103888f-2f4b-4129-983d-634f10965bb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMTEyMTIsIm5iZiI6MTcyODMxMDkxMiwicGF0aCI6Ii8zOTU2MTUyMy8zNzQxOTQ2NDMtZjEwMzg4OGYtMmY0Yi00MTI5LTk4M2QtNjM0ZjEwOTY1YmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDE0MjE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YWE2NTkyOWM2YmQ1NjEwNTkxODAwZDQyZWE5YTc1OGE2ZDQzODhkYjBjODdhYmU0NDMxOTg5Y2NiODFmNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pCzW_b07FasoottGrE_7xeLH_T5oXLnpLAf-qIirL1Q">

You are right.  But it's faster for me to change it myself: https://github.com/yungyuc/nsdhw_24au/commit/ed6f48bf0412b8a5f9324cd055c49a4906700e8c