Project proposal
yungyuc/nsdhw_24au pull request #70
Opened 2024-09-25 11:25 UTC by YaoKuang

---
A good PR should include the following parts:

- [ ] Provide a clear title
- [ ] Provide meaningful descriptions in the PR and the commit logs
- [ ] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [ ] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [ ] Exclude irrelevant files, such as binaries, text files, or dot files
- [ ] Make sure tests/CI pass

2024-09-27 13:20 UTC, yungyuc requested changes
Please elaborate what numerical problems do you want to solve with the project.  I do not see a project name nor a project repository.

2024-10-05 13:27 UTC, yungyuc commented
@YaoKuang , any updates?

2024-10-07 10:32 UTC, yungyuc commented
@YaoKuang , please update as soon as possible.  I will stop accepting proposals any time.

2024-10-07 11:11 UTC, YaoKuang commented
老師您好:

剛剛有更新為您的範例提案，謝謝老師的指導!

陳瑶光敬上

Yung-Yu Chen ***@***.***> 於 2024年10月7日 週一 下午6:33寫道：

> @YaoKuang <https://github.com/YaoKuang> , please update as soon as
> possible. I will stop accepting proposals any time.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/yungyuc/nsdhw_24au/pull/70#issuecomment-2396544336>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU7I5LY5IHARDU6W7FVWGYLZ2JPO5AVCNFSM6AAAAABO2J37BKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJWGU2DIMZTGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-07 11:21 UTC, yungyuc requested changes
When requesting the next review, make a global comment summarizing your change.

- [ ] Resolve merge confclit.
- [ ] Use reStructuredText format.
- [ ] Use less than 80 characters in a line.  Long lines are hard to comment and review.
- [ ] You may use the sample topics, but have to write your own proposal.  You may not copy and paste.

A fully-fledged array library like SimpleArray may take a couple of months.  It will be extremely hard to make a decent presentation without heavily modifying the sample proposal.

2024-10-07 11:21 UTC, yungyuc commented on project/YaoKuang/README.rst
> +SimpleArray for Multi-Dimensional Field
Please use reStructuredText format to typeset.

2024-10-07 11:21 UTC, yungyuc commented on project/YaoKuang/README.rst
> +(Modmesh) SimpleArray: a simple C++ library for multi-dimensional arrays that provide seamless interface with numpy ndarray. Download this file.
Don't copy and paste.  You can follow the example topic, but should write your own proposal.

2024-10-07 11:23 UTC, yungyuc commented
@tigercosmos, if you have time, would you please help @YaoKuang to modify her project proposal?  She is taking the course this semester and need some help.

2024-10-07 11:25 UTC, yungyuc requested changes

2024-10-07 11:25 UTC, yungyuc commented on project/YaoKuang/README.rst
> +SimpleArray is part of modmesh, and the code is house in its repository: https://github.com/solvcon/modmesh
I strongly suggest you to create your own repository for code development.  It takes significant efforts to get familiar with modmesh development flow.

2024-10-07 15:30 UTC, tigercosmos commented
@YaoKuang, you might want to explore a "new" topic for the project. It doesn't have to be something big—any small topic you're interested in is fine. If you'd prefer, you could also work on extending or improving the modmesh project, but keep in mind that getting familiar with the codebase could be a bit challenging at first. Starting your own project might be easier to meet the project requirements, and you can also check out what others are working on for inspiration.

2024-10-10 06:48 UTC, yungyuc commented
@YaoKuang , I know you have sent me an email, but it is not acceptable that you are not paying attention to what I have asked everyone to do for their proposal PRs, e.g., https://github.com/yungyuc/nsdhw_24au/pull/47#pullrequestreview-2312311989.  Please improve.  I don't really how to start review your proposal.

2024-10-10 13:27 UTC, closed without merging

2024-10-10 13:27 UTC, yungyuc commented
I stop accepting proposal.