HW2 submitted by Sean20405 (Attempt 1)
yungyuc/nsdhw_24au pull request #82
Opened 2024-10-03 05:44 UTC by Sean20405

---
In this PR, I've finished HW2, including reimplement class `Line` (Q1) and calculate angle as well as using `pybind11` and `pytest` (Q2).

A good PR should include the following parts:

- [x] Provide a clear title
- [x] Provide meaningful descriptions in the PR and the commit logs
- [x] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [x] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [x] Exclude irrelevant files, such as binaries, text files, or dot files
- [x] Make sure tests/CI pass

2024-10-03 09:32 UTC, ThreeMonth03 requested changes
- [ ] Please remove the unnecessary files.

2024-10-03 09:32 UTC, ThreeMonth03 commented on hw2/Sean20405/validate.sh
> +# vim: set fenc=utf8 ff=unix et sw=2 ts=2 sts=2:
Don't submit the validate script.

2024-10-03 09:32 UTC, ThreeMonth03 commented on hw2/Sean20405/golden.txt
> +point 2: x = 2 y = 5
Don't submit golden text.

2024-10-03 13:18 UTC, Sean20405 commented
OK. I've removed them!

2024-10-04 10:16 UTC, ThreeMonth03 approved these changes
Thanks, the pull request looks better now.

2024-10-04 10:16 UTC, merged