Lien shark hw2 attempt1
yungyuc/nsdhw_24au pull request #84
Opened 2024-10-03 15:43 UTC by LienShark

---
A good PR should include the following parts:

- [ ] Provide a clear title
- [ ] Provide meaningful descriptions in the PR and the commit logs
- [ ] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [ ] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [ ] Exclude irrelevant files, such as binaries, text files, or dot files
- [ ] Make sure tests/CI pass

2024-10-04 10:19 UTC, ThreeMonth03 requested changes
- [ ] Remove the unrelated files in hw2.

2024-10-04 10:19 UTC, ThreeMonth03 commented on project/LienShark/Readme.rst
> +
Please don't submit your project proposal to this pull request.

2024-10-04 10:20 UTC, ThreeMonth03 commented
By the way, you could try to rebase and squash the commit to make your git history clear.

2024-10-04 13:21 UTC, LienShark commented on project/LienShark/Readme.rst
> +
Do you mean the  unrelated files you refer to as the readme file from project/LienShark/readme.rst?

2024-10-04 13:44 UTC, ThreeMonth03 commented on project/LienShark/Readme.rst
> +
> Do you mean the unrelated files you refer to as the readme file from project/LienShark/readme.rst?

Yes, please remove your project proposal to this pull request.

2024-10-05 05:23 UTC, LienShark commented
@ThreeMonth03 I remove the unrelated files, please you check it , thanks TA

2024-10-05 11:01 UTC, ThreeMonth03 commented
> @ThreeMonth03 I remove the unrelated files, please you check it , thanks TA

Could you please submit the url of this pull request to E3 entry?

2024-10-05 15:46 UTC, LienShark commented
@ThreeMonth03 of course! I will do this right now, thanks

2024-10-07 04:40 UTC, ThreeMonth03 approved these changes
LGTM.

2024-10-07 04:40 UTC, merged