Try to push a new pr annd cleann my term project's commit
yungyuc/nsdhw_24au pull request #94
Opened 2024-10-08 18:53 UTC by LienShark

---
A good PR should include the following parts:

- [ ] Provide a clear title
- [ ] Provide meaningful descriptions in the PR and the commit logs
- [ ] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [ ] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [ ] Exclude irrelevant files, such as binaries, text files, or dot files
- [ ] Make sure tests/CI pass

2024-10-08 19:15 UTC, LienShark commented
I sincerely apologize for having to create a new pull request. I accidentally deleted the old remote branch, and since I am not entirely sure which branch matches it, I didn’t want to take any chances and risk causing further issues. I greatly appreciate everyone’s help!

In this submission, I’ve made the following changes:

I’ve added my entry to project/readme.rst.
I’ve provided further explanation on how I handled large matrices using incremental SVD and memory mapping to solve the problem.
I’ve clarified that the idea of working with million-row matrices was inspired by LLM models. This is a challenge I want to take on, though it’s just a goal. The fundamental issue is improving computation speed for large matrices.
I’ve added baseline comparisons, such as numpy.lineal.svd() and sklearn.decomposition.PCA().

2024-10-08 23:22 UTC, yungyuc requested changes
- [x] [`L86`](https://github.com/yungyuc/nsdhw_24au/pull/94/files#diff-fec19e96fbfc351f95b3ac05432fbca60819a9075c25d6a8e59b4b783929c7aaR86): Specify how to deal with matrix majoring.

2024-10-08 23:22 UTC, yungyuc commented on project/LienShark/Readme.rst
> +**1. Input and Output:**
I still did not see how you propose to deal with [array majoring](https://yyc.solvcon.net/en/latest/nsd/04matrix/matrix.html#row-major-2d-array).  I have been asking for this for [more than 3 weeks](https://github.com/yungyuc/nsdhw_24au/pull/47#pullrequestreview-2312311989).  Please specify how will you address it.  Please respond in a comment and update the proposal accordingly as soon as possible.

2024-10-08 23:24 UTC, yungyuc commented
> I sincerely apologize for having to create a new pull request. I accidentally deleted the old remote branch, and since I am not entirely sure which branch matches it, I didn’t want to take any chances and risk causing further issues. I greatly appreciate everyone’s help!
> 
> In this submission, I’ve made the following changes:
> 
> 1.I’ve added my entry to project/readme.rst. 2.I’ve provided further explanation on how I handled large matrices using incremental SVD and memory mapping to solve the problem. 3.I’ve clarified that the idea of working with million-row matrices was inspired by LLM models. This is a challenge I want to take on, though it’s just a goal. The fundamental issue is improving computation speed for large matrices. 4.I’ve added baseline comparisons, such as numpy.lineal.svd() and sklearn.decomposition.PCA().

It's hard for me to see where you made the changes.  You should have added inline comments to highlight the points.

2024-10-08 23:26 UTC, yungyuc commented
This PR succeeds #47.

2024-10-10 05:02 UTC, LienShark commented on project/README.rst
> +    https://github.com/LienShark/EigenApproWithGersgorin
1.added my entry to project/readme.rst.

2024-10-10 06:11 UTC, ThreeMonth03 reviewed
I have some quick questions.

2024-10-10 06:11 UTC, ThreeMonth03 commented on project/LienShark/Readme.rst
> +  - **C++:**  I will use row-major order for better memory access.
Are all C++ matrices in row-major order?

2024-10-10 06:11 UTC, ThreeMonth03 commented on project/LienShark/Readme.rst
> +  - **Python (NumPy):** I will use column-major order for optimized operations.
Why are the numpy matrices in column-major order instead of row-major order?

2024-10-10 06:46 UTC, yungyuc commented
@LienShark are you ready for review?  You did not follow what I asked you to do: https://github.com/yungyuc/nsdhw_24au/pull/47#pullrequestreview-2312311989 and I am baffled.

2024-10-10 11:19 UTC, LienShark commented
> @LienShark are you ready for review? You did not follow what I asked you to do: [#47 (review)](https://github.com/yungyuc/nsdhw_24au/pull/47#pullrequestreview-2312311989) and I am baffled.

sorry , I am trying to adjust my proposal and I will update  it as soon as possible

2024-10-10 12:04 UTC, LienShark commented
I show why I want to use row-major and show some c++ code to explain how to do, thanks for everyone's help

2024-10-10 12:09 UTC, ThreeMonth03 reviewed
- [ ] Write the method of the output matrix majoring.

2024-10-10 12:09 UTC, ThreeMonth03 commented on project/LienShark/Readme.rst
>    2. Approximate eigenvalues estimated using the Gersgorin Theorem, and the low-dimensional matrix reduced by PCA.
Is the output matrix in a row-majoring? Please write it to your proposal.

2024-10-10 12:37 UTC, LienShark commented
I show some c++ code to explain how to do in my output , thanks

2024-10-10 12:56 UTC, ThreeMonth03 reviewed
- [ ] Proofread the sentence.

2024-10-10 12:56 UTC, ThreeMonth03 commented on project/LienShark/Readme.rst
> +  the Output will also row-major,because I want my term project has consistent
Could you please proofread this sentence with ChatGPT?

2024-10-10 13:05 UTC, LienShark commented
@yungyuc Did I meet the requirements? Or is there anything that still needs to be changed and strengthened?
@ThreeMonth03 I modified my sentence about the output

2024-10-10 13:16 UTC, yungyuc approved these changes
It's OK.  But be reminded, @LienShark, you did not know very well about the problem you propose to deal with.  You may have hard time writing code and making slides.

2024-10-10 13:16 UTC, yungyuc commented on project/LienShark/Readme.rst
> +  For e.g: Today, if I need to process a matrix larger than 1000x1000, I would first load a portion of it, and then incrementally update the SVD one row at a time
The progressive reading (updating rows/columns one by one) works for both row- and column-majoring.  Do not hold the wrong idea that row-majoring is better for the progressive reading.

2024-10-10 13:16 UTC, merged